name: Test MCP Servers

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-nodejs:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Install Node.js dependencies
      run: |
        cd mcp-server-obsidian && npm install
        cd ../mcp-server-media && npm install
        
    - name: Run Node.js tests
      run: node test-quick.js
      
  test-python:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        pip install mcp transformers huggingface-hub aiohttp requests
        
    - name: Test Python server syntax
      run: |
        cd mcp-server-huggingface
        python -m py_compile src/mcp_server_huggingface/server.py
        echo "✅ Python syntax validation passed"